uploads = []
outputs = []

[[generated]]
id = "Y1S4li9-Px-ZF1o8ZgdQ4"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "iQ9wDAQimQ2Gynr8ccYaE"
uri = "file://artifacts/mobile/assets/images/splash.png"
type = "image"
title = "generated_image"
